project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('stores.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stores/urls.py
from django.urls import path
from stores import views

app_name = 'stores'

urlpatterns = [
    path('', views.index, name="index"),
    path('add_product/', views.add_product, name="add_product"),
    path('remove_product/<int:_id>', views.remove_product, name="remove_product"),
    path('update_product/<int:_id>', views.update_product, name="update_product"),
    path('all_employees/', views.all_employees, name="all_employees"),
    path('add_employee/', views.add_employee, name="add_employee"),
    path('employee_detail/<int:_id>/',
         views.employee_detail, name="employee_detail"),
    path('remove_employee/<int:_id>/',
         views.remove_employee, name="remove_employee"),
    path('update_employee/<int:_id>/',
         views.update_employee, name="update_employee"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
]

users/urls.py
from django.urls import path
from users import views

app_name = 'users'


urlpatterns = [
    path('', views.index, name="index"),
    path('add_user/', views.add_user, name="add_user"),
    path('update_user/<int:_id>/', views.update_user, name="update_user"),
    path('remove_user/<int:_id>/', views.remove_user, name="remove_user")
]

stores/models.py
from django.db import models
from django.contrib.auth.models import User
from utils.resize_image import resize_image


class Store(models.Model):
    class Meta:
        verbose_name = 'Store'
        verbose_name_plural = 'Stores'

    name = models.CharField(max_length=50)
    description = models.CharField(max_length=255, blank=True)
    location = models.CharField(max_length=255, blank=True)
    owner = models.OneToOneField(
        User, on_delete=models.SET_NULL, null=True)

    def __str__(self) -> str:
        return self.name


class Employee(models.Model):
    class Meta:
        verbose_name = 'Employee'
        verbose_name_plural = 'Employees'

    name = models.CharField(max_length=155)
    age = models.PositiveIntegerField(default=18)
    function = models.CharField(max_length=50)
    email = models.EmailField(max_length=100, null=True)
    store = models.ForeignKey(
        'Store', on_delete=models.SET_NULL, blank=True,
        null=True, default=None,
    )

    def __str__(self) -> str:
        return self.name


class StoreProduct(models.Model):
    class Meta:
        verbose_name = 'StoreProduct'
        verbose_name_plural = 'StoreProducts'

    name = models.CharField(max_length=255)
    short_description = models.TextField(max_length=255, blank=True)
    long_description = models.TextField(blank=True)
    price = models.FloatField()
    stock = models.PositiveIntegerField()
    store = models.ForeignKey(
        Store, on_delete=models.CASCADE
    )
    image = models.ImageField(blank=True, upload_to='images/%Y/%m')

    def save(self, *args, **kwargs) -> None:
        super().save(*args, **kwargs)

        if self.image:
            resize_image(self.image)

    def __str__(self) -> str:
        return self.name

stores/forms.py
from django import forms
from stores import models


class AddProductForm(forms.ModelForm):
    name = forms.CharField(
        required=True,
        max_length=255,
        help_text='Required.',
        error_messages={
            'max_length': 'Please, add less than 255 letters.'
        }
    )
    price = forms.FloatField(required=True, min_value=0, help_text='Required.',)
    stock = forms.IntegerField(
        min_value=0, required=True, help_text='Required.',)
    image = forms.ImageField(
        widget=forms.FileInput(
            attrs={
                'accept': 'image/*',
            }
        ),
        required=False
    )

    class Meta:
        model = models.StoreProduct
        fields = ("name", "short_description",
                  "long_description", "price", "stock", "store", "image")


class AddEmployeeForm(forms.ModelForm):
    name = forms.CharField(
        required=True,
        min_length=3,
        max_length=100,
        help_text='Required.',
        error_messages={
            'min_length': 'Please, add more than 2 letters.'
        }
    )
    age = forms.IntegerField(
        min_value=16,
        max_value=100,
        required=True,
        help_text='Required.',
        error_messages={
            'min_value': 'Min Age 16 years.',
            'max_value': 'Max Age 100 years.'
        }
    )
    function = forms.CharField(
        required=True,
        min_length=2,
        max_length=50,
        help_text='Required.'
    )

    class Meta:
        model = models.Employee
        fields = ("name", "age", "function", "email", "store",)

stores/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.http import Http404
from django.contrib import auth
from stores import models
from stores.forms import AddEmployeeForm, AddProductForm
from django.contrib.auth.forms import AuthenticationForm


def index(request):
    products = models.StoreProduct.objects.all()

    return render(
        request,
        'stores/index.html',
        {
            'products': products
        }
    )


@login_required(login_url="stores:login")
def add_product(request):
    form_action = reverse('stores:add_product')

    if request.method == 'POST':
        form = AddProductForm(request.POST, request.FILES)

        context = {
            'form': form,
            'form_action': form_action
        }

        if form.is_valid():
            product = form.save(commit=False)
            product.save()
            return redirect('stores:index')

        return render(
            request,
            'stores/add_product.html',
            context
        )

    context = {
        'form': AddProductForm(),
        'form_action': form_action,
    }

    return render(
        request,
        'stores/add_product.html',
        context
    )


@login_required(login_url="stores:login")
def update_product(request, _id):
    product = get_object_or_404(models.StoreProduct, pk=_id)

    form = AddProductForm(instance=product)

    if request.method == 'POST':
        form = AddProductForm(
            data=request.POST, files=request.FILES, instance=product)

        if form.is_valid():
            form.save()
            return redirect('stores:update_product', _id=product.pk)

        return render(
            request,
            'stores/add_product.html',
            {
                'form': form,
            }
        )

    return render(
        request,
        'stores/add_product.html',
        {
            'form': form,
        }
    )


@login_required(login_url="stores:login")
def remove_product(request, _id):
    product = get_object_or_404(models.StoreProduct, pk=_id)

    confirmation = request.POST.get('confirmation', 'no')

    if confirmation == 'yes':
        product.delete()
        return redirect('stores:index')

    return render(
        request,
        'stores/remove_product.html',
        {
            'product': product,
            'confirmation': confirmation,
        }
    )


@login_required(login_url="stores:login")
def all_employees(request):
    employees = models.Employee.objects.all()

    context = {
        'employees': employees
    }

    return render(
        request,
        'stores/all_employees.html',
        context
    )


@login_required(login_url="stores:login")
def add_employee(request):
    form_action = reverse('stores:add_employee')

    if request.method == 'POST':
        form_employee = AddEmployeeForm(request.POST)

        context = {
            'form_employee': form_employee,
            'form_action': form_action
        }

        if form_employee.is_valid():
            employee = form_employee.save(commit=False)
            employee.save()
            return redirect('stores:all_employees')

        return render(
            request,
            'stores/add_employee.html',
            context
        )

    context = {
        'form': AddEmployeeForm(),
        'form_action': form_action,
    }

    return render(
        request,
        'stores/add_employee.html',
        context
    )


@login_required(login_url="stores:login")
def update_employee(request, _id):
    employee = get_object_or_404(models.Employee, pk=_id)

    form = AddEmployeeForm(instance=employee)

    if request.method == 'POST':
        form = AddEmployeeForm(
            data=request.POST, files=request.FILES, instance=employee)

        if form.is_valid():
            form.save()
            return redirect('stores:update_employee', _id=employee.pk)

        return render(
            request,
            'stores/add_employee.html',
            {
                'form': form,
            }
        )

    return render(
        request,
        'stores/add_employee.html',
        {
            'form': form,
        }
    )


@login_required(login_url="stores:login")
def employee_detail(request, _id):
    employee = get_object_or_404(models.Employee, pk=_id)

    return render(
        request,
        'stores/employee_detail.html',
        {
            'employee': employee,
        }
    )


@login_required(login_url="stores:login")
def remove_employee(request, _id):

    employee = get_object_or_404(models.Employee, pk=_id)

    if employee.function == 'Owner':
        raise Http404()

    confirmation = request.POST.get('confirmation', 'no')

    if confirmation == 'yes':
        employee.delete()
        return redirect('stores:all_employees')

    return render(
        request,
        'stores/remove_employee.html',
        {
            'employee': employee,
            'confirmation': confirmation,
        }
    )


def login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        if not username or not password:
            return redirect('stores:login')

        user = auth.authenticate(
            request, username=username, password=password
        )

        if user:
            auth.login(request, user=user)
            return redirect('stores:index')
        else:
            return redirect('stores:login')

    return render(
        request,
        'stores/login.html'
    )


@login_required(login_url="stores:login")
def logout(request):

    auth.logout(request)
    return redirect('stores:login')

stores/templates/stores/add_employee.html
{% include 'stores/partials/_head.html' %}
<body>
    <header class="header" id="header">
        <nav class="nav-container">
            <div class="nav_menu" id="nav-menu">
                <ul class="nav_list">
                    <li class="nav_item">
                        <a href="{% url 'stores:all_employees' %}" class="nav_link active-link">Employees</a>
                    </li>
                    <li class="nav_item">
                        <a href="{% url 'stores:logout' %}" class="nav_link">Logout</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <section class="form-employee">
        <form action="{{ form_action }}" method="POST">
            {% csrf_token %}
            <div class="form-content">
                {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        {{ field.errors }}
    
                        {% if field.help_text %}
                            <p class="help-text">
                                {{ field.help_text }}
                            </p>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
    
            {% if form.non_field_errors %}
                <div class="form-content">
                    <div class="form-group">
                        <div class="message error">
                            {{ form.non_field_errors }}
                        </div>
                    </div>
                </div>
            {% endif %}
    
            <div class="form-content">
                <div class="form-group">
                    <button class="btn" type="submit">Send</button>
                </div>
            </div>
        </form>
    </section>

    {% include 'stores/partials/_footer.html' %}
</body>
</html>

stores/templates/stores/add_product.html
{% include 'stores/partials/_head.html' %}
<body>

    <header class="header" id="header">
        <nav class="nav-container">
            <div class="nav_menu" id="nav-menu">
                <ul class="nav_list">
                    <li class="nav_item">
                        <a href="{% url 'stores:index' %}" class="nav_link active-link">Products</a>
                    </li>
                    <li class="nav_item">
                        <a href="{% url 'stores:logout' %}" class="nav_link">Logout</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <section class="section form-product">
        <form action="{{ form_action }}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-content">
                {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        {{ field.errors }}
    
                        {% if field.help_text %}
                            <p class="help-text">
                                {{ field.help_text }}
                            </p>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
    
            {% if form.non_field_errors %}
                <div class="form-content">
                    <div class="form-group">
                        <div class="message error">
                            {{ form.non_field_errors }}
                        </div>
                    </div>
                </div>
            {% endif %}
    
            <div class="form-content">
                <div class="form-group">
                    <button class="btn" type="submit">Send</button>
                </div>
            </div>
        </form>
    </section>

    {% include 'stores/partials/_footer.html' %}
    
</body>
</html>

stores/templates/stores/all_employees.html
{% include 'stores/partials/_head.html' %}
<body>

    <header class="header" id="header">
        <nav class="nav-container">
            <div class="nav_menu" id="nav-menu">
                <ul class="nav_list">
                    <li class="nav_item">
                        <a href="{% url 'stores:index' %}" class="nav_link active-link">Products</a>
                    </li>
                    <li class="nav_item">
                        <a href="{% url 'stores:add_employee' %}" class="nav_link">Add Employee</a>
                    </li>
                    <li class="nav_item">
                        <a href="{% url 'users:index' %}" class="nav_link">Users</a>
                    </li>
                    <li class="nav_item">
                        <a href="{% url 'stores:logout' %}" class="nav_link">Logout</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    
    {% include 'stores/partials/_employee.html' %}

    {% include 'stores/partials/_footer.html' %}

</body>
</html>

stores/templates/stores/employee_detail.html
{% include 'stores/partials/_head.html' %}
<body>
    <header class="header" id="header">
        <nav class="nav-container">
            <div class="nav_menu" id="nav-menu">
                <ul class="nav_list">
                    <li class="nav_item">
                        <a href="{% url 'stores:all_employees' %}" class="nav_link active-link">Employees</a>
                    </li>
                    <li class="nav_item">
                        <a href="{% url 'stores:add_employee' %}" class="nav_link">Add Employee</a>
                    </li>
                    <li class="nav_item">
                        <a href="{% url 'stores:logout' %}" class="nav_link">Logout</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <section class="section details">
        <div class="employee-detail">
            <div class="detail">
                <h1 class="detail-name">
                    {{ employee.name }}
                </h1>
                <div class="detail-info">
                    <h2 class="detail-age">Age: {{ employee.age }}</h2>
                    <h2 class="detail-function">Function: {{ employee.function }}</h2>
                    <h2 class="detail-store">Store: {{ employee.store }}</h2>
                </div>
                <div class="employee-remove">
                    {% if user.is_authenticated and employee.function != 'Owner' %}
                        <a class="btn-remove-employee" href="{% url 'stores:remove_employee' employee.id %}">Remove</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>

    {% include 'stores/partials/_footer.html' %}

</body>
</html>

stores/templates/stores/index.html
{% include 'stores/partials/_head.html' %}
<body>

    <header class="header" id="header">
        <nav class="nav-container">
            <div class="nav_menu" id="nav-menu">
                <ul class="nav_list">
                    {% if user.is_authenticated %}
                        <li class="nav_item">
                            <a href="{% url 'stores:add_product' %}" class="nav_link">Add Product</a>
                        </li>
                        <li class="nav_item">
                            <a href="{% url 'stores:all_employees' %}" class="nav_link">Employees</a>
                        </li>
                        <li class="nav_item">
                            <a href="{% url 'stores:logout' %}" class="nav_link">Logout</a>
                        </li>
                    {% else %}
                        <li class="nav_item">
                            <a href="{% url 'stores:login' %}" class="nav_link">Login</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>

    <section class="section products">
        {% for product in products %}
            <div class="product">
                <h1 class="p-text product-title">{{ product.name }}</h1>
                <p class="p-text product-desc">{{ product.short_description }}</p>
                <p class="p-text product-desc">{{ product.long_description }}</p>
                <h2 class="p-text product-price">Price: {{ product.price }}</h2>
                <h2 class="p-text product-stock">Stock: {{ product.stock }}</h2>
                {% if product.image %}
                <p>
                    <img class="product-image" src="{{ product.image.url }}" alt="{{ product.short_description }}">
                </p>
                {% endif %}
                <h2 class="p-text product-store">{{ product.store }}</h2>
                {% if user.is_authenticated %}
                    <div class="product-links">
                        <a class="product-link" href="{% url 'stores:remove_product' product.id %}">Remove</a>
                        <a class="product-link" href="{% url 'stores:update_product' product.id %}">Update</a>
                    </div>
                {% endif %}
            </div>
        {% endfor %}
    </section>

    {% include 'stores/partials/_footer.html' %}
    
</body>
</html>

stores/templates/stores/login.html
{% include 'stores/partials/_head.html' %}
<body>

    <header class="header" id="header">
        <nav class="nav-container">
            <div class="nav_menu" id="nav-menu">
                <ul class="nav_list">
                    <li class="nav_item">
                        <a href="{% url 'stores:index' %}" class="nav_link active-link">Products</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav_item">
                            <a href="{% url 'stores:logout' %}" class="nav_link">Logout</a>
                        </li>
                    {% else %}
                        <li class="nav_item">
                            <a href="{% url 'stores:login' %}" class="nav_link">Login</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>

    <section class="section login">
        {% if user.is_authenticated %}
            <div class="login-content">
                <p class="login-text">
                    Logged as {{ user.username }}.
                    Click <a href="{% url 'stores:logout' %}">here</a>
                    to logout.
                </p>
            </div>
        {% else %}
            <form action="{% url 'stores:login' %}" method="post">
                {% csrf_token %}
                <div class="form-content">
                    <div class="form-group">
                        <label for="input1">Username</label>
                        <input type="text" id="input1" placeholder="Username" name="username">
                    </div>
                    <div class="form-group">
                        <label for="input2">Password</label>
                        <input type="password" id="input2" placeholder="Password" name="password">
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-add_user">Login</button>
                    </div>
                </div>
            </form>
        {% endif %}
    </section>

    {% include 'stores/partials/_footer.html' %}

</body>
</html>

stores/templates/stores/remove_employee.html
{% include 'stores/partials/_head.html' %}
<body>
   
    <header class="header" id="header">
        <nav class="nav-container">
            <div class="nav_menu" id="nav-menu">
                <ul class="nav_list">
                    <li class="nav_item">
                        <a href="{% url 'stores:all_employees' %}" class="nav_link active-link">Employees</a>
                    </li>
                    <li class="nav_item">
                        <a href="{% url 'stores:add_employee' %}" class="nav_link">Add Employee</a>
                    </li>
                    <li class="nav_item">
                        <a href="{% url 'stores:logout' %}" class="nav_link">Logout</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <section class="section remove_section">
        <div class="form-remove">
            <h1 class="employee_name">Delete: {{ employee.name }}</h1>
            <form action="{% url 'stores:remove_employee' employee.id %}" method="POST">
                {% csrf_token %}
                {% if confirmation == 'no' %}
                    <input type="hidden" name="confirmation" value="yes">
                    <button class="btn btn-option btn-delete" type="submit">Confirm?</button>
                {% else %}
                    <button class="btn btn-option btn-delete" type="submit">Delete</button>
                {% endif %}
            </form>
        </div>
    </section>

    {% include 'stores/partials/_footer.html' %}
    
</body>
</html>

stores/templates/stores/remove_product.html
{% include 'stores/partials/_head.html' %}
<body>

    <header class="header" id="header">
        <nav class="nav-container">
            <div class="nav_menu" id="nav-menu">
                <ul class="nav_list">
                    <li class="nav_item">
                        <a href="{% url 'stores:index' %}" class="nav_link active-link">Products</a>
                    </li>

                    <li class="nav_item">
                        <a href="{% url 'stores:add_product' %}" class="nav_link">Add Product</a>
                    </li>

                    <li class="nav_item">
                        <a href="{% url 'stores:logout' %}" class="nav_link">Logout</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <section class="section remove_section">
        <div class="form-remove">
            <h1 class="product_name">Delete: {{ product.name }}</h1>
            <form action="{% url 'stores:remove_product' product.id %}" method="POST">
                {% csrf_token %}
                {% if confirmation == 'no' %}
                    <input type="hidden" name="confirmation" value="yes">
                    <button class="btn btn-option btn-delete" type="submit">Confirm?</button>
                {% endif %}
            </form>
        </div>
    </section>

    {% include 'stores/partials/_footer.html' %}

</body>
</html>