project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('stores.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stores/urls.py
from django.urls import path
from stores import views

app_name = 'stores'

urlpatterns = [
    path('', views.index, name="index"),
    path('add_product/', views.add_product, name="add_product"),
    path('remove_product/<int:_id>', views.remove_product, name="remove_product"),
    path('update_product/<int:_id>', views.update_product, name="update_product"),
    path('all_employees/', views.all_employees, name="all_employees"),
    path('add_employee/', views.add_employee, name="add_employee"),
    path('employee_detail/<int:_id>/',
         views.employee_detail, name="employee_detail"),
    path('remove_employee/<int:_id>/',
         views.remove_employee, name="remove_employee"),
    path('update_employee/<int:_id>/',
         views.update_employee, name="update_employee"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
]

users/urls.py
from django.urls import path
from users import views

app_name = 'users'


urlpatterns = [
    path('', views.index, name="index"),
    path('add_user/', views.add_user, name="add_user"),
    path('update_user/<int:_id>/', views.update_user, name="update_user"),
    path('remove_user/<int:_id>/', views.remove_user, name="remove_user")
]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.models import User


class AddUserForm(forms.ModelForm):
    username = forms.CharField(required=True, min_length=4, max_length=50)
    first_name = forms.CharField(required=True, min_length=3, max_length=50)
    last_name = forms.CharField(required=True, min_length=3, max_length=100)
    email = forms.EmailField(required=True)
    password = forms.CharField(required=True, widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name",
                  "email", "password")

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import Http404
from users.forms import AddUserForm


@login_required(login_url='stores:login')
def index(request):
    users = User.objects.all()

    return render(
        request,
        'users/index.html',
        {
            'users': users
        }
    )


@login_required(login_url='stores:login')
def add_user(request):
    form_action = reverse('users:add_user')

    if request.method == 'POST':
        form_user = AddUserForm(request.POST)

        context = {
            'form_user': form_user,
            'form_action': form_action
        }

        if form_user.is_valid():
            user = form_user.save(commit=False)
            password = form_user.cleaned_data.get('password')
            user.set_password(password)
            user.save()
            return redirect('users:index')

        return render(
            request,
            'users/add_user.html',
            context
        )

    context = {
        'form_user': AddUserForm(),
        'form_action': form_action,
    }

    return render(
        request,
        'users/add_user.html',
        context
    )


@login_required(login_url='stores:login')
def update_user(request, _id):
    user = get_object_or_404(User, pk=_id)

    if user.is_superuser:
        raise Http404

    form = AddUserForm(instance=user)

    if request.method == 'POST':
        form = AddUserForm(
            data=request.POST, instance=user)

        if form.is_valid():
            form.save()
            return redirect('users:update_user', _id=user.pk)

        return render(
            request,
            'users/add_user.html',
            {
                'form_user': form,
            }
        )

    return render(
        request,
        'users/add_user.html',
        {
            'form_user': form,
        }
    )


@login_required(login_url='stores:login')
def remove_user(request, _id):
    user = get_object_or_404(User, pk=_id)

    if user.is_superuser:
        raise Http404

    confirmation = request.POST.get('confirmation', 'no')

    if confirmation == 'yes':
        user.delete()
        return redirect('users:index')

    return render(
        request,
        'users/remove_user.html',
        {
            'user': user,
            'confirmation': confirmation,
        }
    )

users/templates/users/add_user.html
{% include 'stores/partials/_head.html' %}
<body>
    <header class="header" id="header">
        <nav class="nav-container">
            <div class="nav_menu" id="nav-menu">
                <ul class="nav_list">
                    <li class="nav_item">
                        <a href="{% url 'users:index' %}" class="nav_link active-link">Users</a>
                    </li>
                    <li class="nav_item">
                        <a href="{% url 'stores:logout' %}" class="nav_link">Logout</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <section class="form-employee">
        <form action="{{ form_action }}" method="POST">
            {% csrf_token %}
            <div class="form-content">
                {% for field in form_user %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        {{ field.errors }}
    
                        {% if field.help_text %}
                            <p class="help-text">
                                {{ field.help_text }}
                            </p>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
    
            {% if form_user.non_field_errors %}
                <div class="form-content">
                    <div class="form-group">
                        <div class="message error">
                            {{ form.non_field_errors }}
                        </div>
                    </div>
                </div>
            {% endif %}
    
            <div class="form-content">
                <div class="form-group">
                    <button class="btn" type="submit">Send</button>
                </div>
            </div>
        </form>
    </section>

    {% include 'users/partials/_footer.html' %}
</body>
</html>

users/templates/users/index.html
{% include 'users/partials/_head.html' %}

<body>
    <header class="header" id="header">
        <nav class="nav-container">
            <div class="nav_menu" id="nav-menu">
                <ul class="nav_list">
                    <li class="nav_item">
                        <a href="{% url 'stores:all_employees' %}" class="nav_link">Employees</a>
                    </li>
                    <li class="nav_item">
                        <a href="{% url 'users:add_user' %}" class="nav_link">Add User</a>
                    </li>
                    <li class="nav_item">
                        <a href="{% url 'stores:logout' %}" class="nav_link">Logout</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <section class="section users">
        {% for user in users %}
            <div class="user_info">
                <div class="user_div">
                    <h1 class="user_pk">{{ user.pk }}</h1>
                    <h1 class="user_username">{{ user }}</h1>
                </div>
                <div class="user_div">
                    <h2 class="user_name">{{ user.first_name }}</h1>
                    <h2 class="user_name">{{ user.last_name }}</h1>
                </div>
                <div class="user_div">
                    <h3 class="user_email">{{ user.email }}</h1>
                </div>
                <div class="user_links">
                    {% if not user.is_superuser %}
                        <a href="{% url 'users:update_user' user.pk %}" class="user_link">Update</a>
                        <a href="{% url 'users:remove_user' user.pk %}" class="user_link">Remove</a>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
    </section>

    {% include 'users/partials/_footer.html' %}
    
</body>
</html>

users/templates/users/remove_user.html
{% include 'users/partials/_head.html' %}
<body>
   
    <header class="header" id="header">
        <nav class="nav-container">
            <div class="nav_menu" id="nav-menu">
                <ul class="nav_list">
                    <li class="nav_item">
                        <a href="{% url 'users:index' %}" class="nav_link active-link">Users</a>
                    </li>
                    <li class="nav_item">
                        <a href="{% url 'users:add_user' %}" class="nav_link">Add User</a>
                    </li>
                    <li class="nav_item">
                        <a href="{% url 'stores:logout' %}" class="nav_link">Logout</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <section class="section remove_section">
        <div class="form-remove">
            <h1 class="employee_name">Delete: {{ user.username }}</h1>
            <form action="{% url 'users:remove_user' user.pk %}" method="POST">
                {% csrf_token %}
                {% if confirmation == 'no' %}
                    <input type="hidden" name="confirmation" value="yes">
                    <button class="btn btn-option btn-delete" type="submit">Confirm?</button>
                {% else %}
                    <button class="btn btn-option btn-delete" type="submit">Delete</button>
                {% endif %}
            </form>
        </div>
    </section>

    {% include 'users/partials/_footer.html' %}
    
</body>
</html>